name: GitHub Security Alerts for Jira

on: workflow_dispatch

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: https://illuminapps.atlassian.net
          JIRA_USER_EMAIL: dialhepachon@gmail.com
          JIRA_API_TOKEN: ${{ secrets.JiraApiToken }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: EEL
          issuetype: Bug
          summary: Build completed for ${{ github.repository }}
          description: Compare branch
      
      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
