name: GitHub Security Alerts for Jira

on: workflow_dispatch

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.5.0
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_TOKEN: ${{ secrets.JiraApiToken }}
          JIRA_HOST: https://illuminapps.atlassian.net
          JIRA_USER: dialhepachon@gmail.com
          JIRA_PROJECT: EEL
